name: macOS

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build-arm64:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Configure
      run: ./configure
    - name: Make
      run: make
    - name: Copy binary
      run: cp lame KoreTools_macos_arm64/lame
    - name: Set name
      run: git config --global user.name "Robbot"
    - name: Set email
      run: git config --global user.email "robbot2019@robdangero.us"
    - name: Commit binary
      id: commit
      continue-on-error: true
      run: git -C KoreTools_macos_arm64 commit -a -m "Update lame binary to $GITHUB_SHA."
    - name: Tag binary
      if: steps.commit.outcome == 'success'
      run: git -C KoreTools_macos_arm64 tag kong_$GITHUB_SHA
    - name: Push binary
      id: push1
      if: steps.commit.outcome == 'success'
      continue-on-error: true
      run: git -C KoreTools_macos_arm64 push https://Kode-Robbot:$ROBBOT_PASS@github.com/Kode/KoreTools_macos_arm64.git main --tags
      env:
        ROBBOT_PASS: ${{ secrets.ROBBOT_PASS }}
    - name: Pull
      if: steps.commit.outcome == 'success' && steps.push1.outcome != 'success'
      run: git -C KoreTools_macos_arm64 pull --no-rebase
    - name: Push binary again
      if: steps.commit.outcome == 'success' && steps.push1.outcome != 'success'
      continue-on-error: true
      run: git -C KoreTools_macos_arm64 push https://Kode-Robbot:$ROBBOT_PASS@github.com/Kode/KoreTools_macos_arm64.git main --tags
      env:
        ROBBOT_PASS: ${{ secrets.ROBBOT_PASS }}

  build-x64:
    runs-on: macos-13

    steps:
    - uses: actions/checkout@v4
    - name: Configure
      run: ./configure
    - name: Make
      run: make
    - name: Copy binary
      run: cp lame KoreTools_macos_x64/lame
    - name: Set name
      run: git config --global user.name "Robbot"
    - name: Set email
      run: git config --global user.email "robbot2019@robdangero.us"
    - name: Commit binary
      id: commit
      continue-on-error: true
      run: git -C KoreTools_macos_x64 commit -a -m "Update lame binary to $GITHUB_SHA."
    - name: Tag binary
      if: steps.commit.outcome == 'success'
      run: git -C KoreTools_macos_x64 tag kong_$GITHUB_SHA
    - name: Push binary
      id: push1
      if: steps.commit.outcome == 'success'
      continue-on-error: true
      run: git -C KoreTools_macos_x64 push https://Kode-Robbot:$ROBBOT_PASS@github.com/Kode/KoreTools_macos_x64.git main --tags
      env:
        ROBBOT_PASS: ${{ secrets.ROBBOT_PASS }}
    - name: Pull
      if: steps.commit.outcome == 'success' && steps.push1.outcome != 'success'
      run: git -C KoreTools_macos_x64 pull --no-rebase
    - name: Push binary again
      if: steps.commit.outcome == 'success' && steps.push1.outcome != 'success'
      continue-on-error: true
      run: git -C KoreTools_macos_x64 push https://Kode-Robbot:$ROBBOT_PASS@github.com/Kode/KoreTools_macos_x64.git main --tags
      env:
        ROBBOT_PASS: ${{ secrets.ROBBOT_PASS }}
